# Generated by Django 4.2 on 2024-02-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textnote",
            name="title",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="textnote",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
